[project]
name = "ui_dataviewer"
version = "0.1.0"
description = "Add a short description here"
authors = ["Kaze Wong <kazewong.physics@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
python = ">=3.12.7,<3.13"
rust = ">=1.81.0,<1.82"
rerun-sdk = ">=0.18.2,<0.19"
